// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/graphaelli/execreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/graphaelli/execreceiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                         metric.Meter
	mu                            sync.Mutex
	registrations                 []metric.Registration
	ExecReceiverErrors            metric.Int64Counter
	ExecReceiverExecutionDuration metric.Float64Histogram
	ExecReceiverExecutions        metric.Int64Counter
	ExecReceiverLogRecords        metric.Int64Counter
	ExecReceiverRestarts          metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ExecReceiverErrors, err = builder.meter.Int64Counter(
		"otelcol_exec_receiver_errors",
		metric.WithDescription("Total number of command execution errors. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExecReceiverExecutionDuration, err = builder.meter.Float64Histogram(
		"otelcol_exec_receiver_execution_duration",
		metric.WithDescription("Duration of command executions. [Development]"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries([]float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 30, 60}...),
	)
	errs = errors.Join(errs, err)
	builder.ExecReceiverExecutions, err = builder.meter.Int64Counter(
		"otelcol_exec_receiver_executions",
		metric.WithDescription("Total number of command executions started. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExecReceiverLogRecords, err = builder.meter.Int64Counter(
		"otelcol_exec_receiver_log_records",
		metric.WithDescription("Total number of log records produced from command output. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExecReceiverRestarts, err = builder.meter.Int64Counter(
		"otelcol_exec_receiver_restarts",
		metric.WithDescription("Total number of streaming command restarts. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
