// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("exec")
	ScopeName = "github.com/graphaelli/execreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
